spring:
  application:
    name: arena_hub
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: ${JWT_EXPIRATION}